name: Publish to npm

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare-runner
      - uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org"
      - run: pnpm oxlint
      - run: pnpm typecheck
      - run: pnpm publish --no-git-checks --provenance
